# Dependencies
plugins:
  - jekyll-sitemap
  #- jekyll-paginate
  #- jekyll-paginate-v2

# File rules
exclude:
  # default excludes
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # custom excludes
  - Makefile
  - Dangerfile
  - LICENSE
  - README.md
  - assets/
  - package.json
  - yarn.lock
  - scripts/
  - .github/

include:
  - .htaccess
  # bootstrap
  - node_modules/bootstrap/dist/css/bootstrap.min.css
  - node_modules/bootstrap/dist/css/bootstrap.min.css.map
  - node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
  - node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map
  # jquery
  - node_modules/jquery/dist/jquery.slim.min.js
  # font awesome
  - node_modules/font-awesome/css/font-awesome.min.css
  - node_modules/font-awesome/fonts/FontAwesome.otf
  - node_modules/font-awesome/fonts/fontawesome-webfont.eot
  - node_modules/font-awesome/fonts/fontawesome-webfont.svg
  - node_modules/font-awesome/fonts/fontawesome-webfont.ttf
  - node_modules/font-awesome/fonts/fontawesome-webfont.woff
  - node_modules/font-awesome/fonts/fontawesome-webfont.woff2

keep_files:
  - .well-known

# Site
permalink: /blog/:year/:month/:day/:title/
img_url: /img
excerpt_separator: <!--excerpt-->
sass:
  style: compressed

# Metadata
title: 'TITLE'
description: 'DESCRIPTION'
url: https://www.MY_SITE.com
logo: /ico/logo.png
timezone: America/Los_Angeles

# Author
author:
  name: 'AUTHOR'
  twitter: TWITTER_USERNAME
  avatar: /ico/avatar.jpg

feeds:
  rss: '/feed.xml'
  json: '/feed.json'
