# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: Danger

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled, edited]

jobs:
  job-main:
    name: Review and Lint
    runs-on: ubuntu-latest
    steps:
      - name: ruby versions
        run: |
          ruby --version
          gem --version

      - name: git checkout
        uses: actions/checkout@v2

      # https://github.com/ruby/setup-ruby
      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      # for danger prose-lint
      - name: python setup
        run: |
          echo "/Users/runner/Library/Python/2.7/bin" >> $GITHUB_PATH

      - name: danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run: bundle exec danger --verbose
